---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: air 
  name: example-app 
spec:
  replicas: 30
  selector:
    matchLabels:
      service: example-app 
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  minReadySeconds: 30
  template:
    metadata:
      labels:
        service: example-app 
    spec:
      containers:

      - name: example-app
        image: dockerregistry.com/example-app:309
        imagePullPolicy: IfNotPresent
        resources:
         limits:
           memory: "8G"
           cpu: "5"
         requests:
           memory: "3G"
           cpu: "1"
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: STARTCMD
          value: "java  -jar app.jar"
        - name: FILEBEAT
          value: "false"
        - name: FILEBEAT_APP_NAME
          value: "example-app "
        - name: FILEBEAT_APP_TOPIC
          value: "air-search-app"
        - name: FILEBEAT_ITI_TOPIC
          value: "airsrch-access"
        - name: NEW_RELIC_APP_NAME
          value: "example-app"
        - name: FILEBEAT_APP_LOGFILE
          value: "/var/log/tomcat7/catalina.out"
        - name: FILEBEAT_ACCESS_LOGFILE 
          value: "/var/log/tomcat7/access.log"



        ports:
        - containerPort: 9080
        readinessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 60
       
      dnsPolicy: "ClusterFirst"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: resource-group
                operator: NotIn
                values:
                - data

---
kind: Service
apiVersion: v1
metadata:
  namespace: air 
  name: example-app 
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    service: example-app
  loadBalancerIP: 10.160.0.3 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9080
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-app
  namespace: air
spec:
  maxReplicas: 120
  minReplicas: 30
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: example-app
  targetCPUUtilizationPercentage: 90
