filebeat.prospectors:
- type: log
  paths:
    - ${FILEBEAT_APP_LOGFILE:/opt/app/logs/application.log}
  fields:
    product: ${FILEBEAT_APP_NAME}
    app_type: java
    env: kube 
    log_topic: ${FILEBEAT_APP_TOPIC}
  #ignore_older: 72h
  fields_under_root: true
  close-inactive: 2h
  scan_frequency: 10s
  exclude_lines: ['^$']
  multiline.pattern: ^[0-9]{2}:[0-9]{2}:[0-9]{2}
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - ${FILEBEAT_ACCESS_LOGFILE:/opt/app/logs/access.*.log}
  fields:
    product: ${FILEBEAT_APP_NAME}
    app_type: java
    env: kube
    log_topic: ${FILEBEAT_ITI_TOPIC:prod-test}
  #ignore_older: 72h
  close-inactive: 2h
  scan_frequency: 10s
  fields_under_root: true



#----------------------------- Kafka output -----------------------------------
output.kafka:
  enabled: true
  hosts: ["example1.com:9092","example2.com:9092"] 
  topic: '%{[log_topic]}'
  version: "0.9.0.1"
  partition.round_robin:
    reachable_only: true
    group_events: 50
  compression: gzip
  client_id: ${HOSTNAME}
logging.level: warning
