apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-team
  namespace: example
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: example
  name: ro
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["", "extensions", "apps","batch"]
  resources: ["deployments", "replicasets", "pods","events","configmaps","secrets","persistentvolumes","persistentvolumeclaims","daemonsets","ingresses","jobs","cronjobs","replicationcontrollers","statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions", "apps","batch"]
  resources: ["deployments"]
  verbs: ["edit","update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ro-binding
  namespace: example
subjects:
- kind: ServiceAccount
  name: example-team
  namespace: example
roleRef:
  kind: Role
  name: ro
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ns-ro
rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: example-ns-ro
subjects:
- kind: ServiceAccount
  name: example-team
  namespace: example
roleRef:
  kind: ClusterRole
  name: ns-ro
  apiGroup: rbac.authorization.k8s.io
