apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: nfs.example.com
    path: "/dara/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: example
  name: pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: pv
  
